settings:
  seed: 2021
  model_name: "efficientnet_v2"

  batch_size: 64
  image_size: [256, 128]
  mixup: True
  label_smooth: True
  margin: 0.3
  center_loss_weight: 0.0005

  # data augmentation
  prob: 0.5
  padding: 10
  re_prob: 0.5

  log_period: 50
  checkpoint_period: 25
  eval_period: 50

  lr_policy:
    name: "adam"
    lr: 0.0001
    momentum: 0.937
    weight_decay: 0.0005
    center_lr: 0.5
    weight_decay_bias: 0.
    bias_lr_factor: 2

  # learning rate scheduling
  steps: [30, 55]
  gamma: 0.1
  warmup_factor: 0.3
  warmup_iters: 500
  warmup_method: "linear"